---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 ! -name 'cgi-bin' -exec rm -rf {} +
    - /bin/cp -a . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git $DEPLOYPATH/.cpanel.yml $DEPLOYPATH/.gitignore
    - /bin/chmod 755 $DEPLOYPATH
